name : Flask App CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - name: Set up python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'

        - name: Install dependencies
          run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt


        - name: Build
          run: |
            echo "Built succesfully"

    test:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - name: Set up python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            
        - name: Test
          run: |
            python3 test_app.py


    deploy:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v2

          - name: Deploy
            run: |
              echo "We're live!!"
        